sudo: required
services:
  - docker

before_install:
  - docker build -t sundar0989/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sundar0989/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t sundar0989/multi-client ./client
  - docker build -t sundar0989/multi-nginx ./nginx
  - docker build -t sundar0989/multi-server ./server
  - docker build -t sundar0989/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push sundar0989/multi-client
  - docker push sundar0989/multi-nginx
  - docker push sundar0989/multi-server
  - docker push sundar0989/multi-worker
